name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# PRs pe latest run ko hi rakho, baaki cancel. time bachta hai.
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Strict lint in CI. If you prefer softer, use `npm run lint`.
      - name: Run ESLint
        run: npm run lint:ci

      - name: Run Prettier check
        run: npx prettier --check .

      # Optional but useful. Fails fast on TS errors even if build would tree-shake it away.
      - name: Type check
        run: npm run typecheck

      # Next.js build (you’re using Turbopack flags in package.json already)
      - name: Build Next.js app
        run: npm run build

      # Cache .next between jobs (speeds up subsequent steps if you add tests/e2e later)
      - name: Cache Next build artifacts
        uses: actions/cache/save@v4
        if: success()
        with:
          path: |
            .next/cache
          key: next-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
